apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    component: elasticsearch
    role: client
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 10.0.0.0/8
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: http
    port: 9200
    protocol: TCP
