apiVersion: v1
kind: PersistentVolume
metadata:
    name: test-cluster-elasticsearch-disk-1
spec:
  capacity:
    storage: 2000G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd-storage-class
  gcePersistentDisk:
    fsType: ext4
    pdName: test-cluster-elasticsearch-disk-1